spring:
  datasource:
    url: jdbc:hsqldb:mem:testDB
    username: sa
    password: sa
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true